from userApp.forms.LoginForm import LoginForm
from userApp.forms.RegisterForm import RegisterForm
from userApp.forms.AnimalForm import AnimalForm
from userApp.forms.CategoryForm import CategoryForm
from userApp.forms.ProviderForm import ProviderForm
from userApp.forms.ManagerForm import ManagerForm
from userApp.forms.CustomerForm import CustomerForm
from userApp.forms.SupplyForm import SupplyForm
from userApp.forms.OrderForm import OrderForm
from userApp.forms.ExcelForm import ExcelForm